# Template for the config file, which should be called config.yml and sit in the same directory as the executable
client:
  # The URL of the OPC-UA server to connect to
  EndpointURL: opc.tcp://localhost:4840
  # Auto accept connections, if this is true, no certificates will be used. Do not set to true in prod!
  Autoaccept: false
  # Maximum number of results to return when reading historical data. 0 for unlimited, though lower numbers give
  # higher reliability, as data is pushed to CDF after each read finishes
  MaxResults: 100
  # Polling interval in ms between each test of changes to a subscribed variable
  # 0 updates at maximum rate set by server
  PollingInterval: 0
  # Time in ms between each attempted reconnect after a disconnect
  # Should not be set too short
  ReconnectPeriod: 5000
  # Global prefix for externalId in CDF. Required, and should be completely unique to prevent name conflicts in CDF.
  GlobalPrefix: gp
  # OPC-UA username, leave blank for anonymous user. (no authentication)
  Username: "username"
  # OPC-UA password
  Password: "password"
  # Use secured connection
  Secure: false
  # Specify prefix on DisplayName to ignore, leave empty for none
  IgnorePrefix:

nsmaps:
  # Map OPC-UA namespaces to prefixes in CDF. 
  # Ex: "urn:cognite:net:server": cns
  # Saves space compared to using the full URL. Using the ns index is not safe
  # If not specified, the full URI is used instead.
  "urn:freeopcua:python:server": fps
  "http://examples.freeopcua.github.io": efg

cognite:
  # The project to connect to in the API
  Project: test
  # Cognite api key
  ApiKey: test
  # The root asset must exist, and will be mapped to the root node in opcua
  # Root assetid to map to root OPC-UA node
  RootAssetId: 0
  # Full name of the namespace of the root node
  # RootNodeNamespace: http://examples.freeopcua.github.io
  RootNodeNamespace:
  # Id of the root node, on the form "i=123" or "s=stringid" etc.
  RootNodeId: i=0
  # Delay in ms between each push of data points to CDF
  DataPushDelay: 1000
  # Debug mode, if true, Extractor will not push to CDF
  Debug: false

logging:
  # Folder for logging output. Leave blank for console only
  LogFolder:
  # Whether or not to log all data output. For debugging only. true/false
  LogData: false

metrics:
  # Leave host or job blank to disable metrics
  # URL of prometheus host, ex my.prometheus.server gives final endpoint my.prometheus.server/metrics/jobs/myjob, 
  URL:
  # Port to connect to on prometheus host
  Job:
  # Prometheus username
  Username:
  # Prometheus password
  Password:
  # Time in ms between each push
  PushInterval: 1000
  # Instance tag for prometheus
  Instance: